data:
  raw_filename: "train.csv"
  ingested_filename: "adult_income_ingested.parquet"
  processed_filename: "adult_income_clean.parquet"
  target_column: "income_>50K"
  columns_to_drop:
    - "fnlwgt"
    - "education"
    - "native-country"
  expected_columns:
    - "age"
    - "workclass"
    - "fnlwgt"
    - "education"
    - "educational-num"
    - "marital-status"
    - "occupation"
    - "relationship"
    - "race"
    - "gender"
    - "capital-gain"
    - "capital-loss"
    - "hours-per-week"
    - "native-country"
    - "income_>50K"
